import mysql.connector
mydb = mysql.connector.connect(
    host='localhost',
    user='root',
    passwd='passwd',
    auth_plugin='mysql_native_password',
    database="LolStats"
)
MyCursor = mydb.cursor()

# Tworzenie tablicy dla Graczy
SQLCreateTablePlayers = """
CREATE TABLE players (
puuid VARCHAR(80) PRIMARY KEY,
name VARCHAR(30),
accountId VARCHAR(80),
id VARCHAR(80),
tag VARCHAR(5),
level INT,
profile_icon INT,
tierSolo VARCHAR(15),
rankSolo VARCHAR(10),
lpSolo INT,
winSolo INT,
loseSolo INT
)"""

# Tworzenie tablicy dla statystyk z gry
SQLCreateTableChampBuild = """
CREATE TABLE champ_build (
id INT AUTO_INCREMENT PRIMARY KEY,
endOfGameResult VARCHAR(20),
gameCreation BIGINT,
gameDuration INT,
gameEndTimestamp BIGINT,
gameId BIGINT,
gameMode VARCHAR(20),
gameStartTimestamp BIGINT,
gameType VARCHAR(20),
gameVersion VARCHAR(20),
mapId INT,
platformId VARCHAR(4),
queueId INT,
tournamentCode VARCHAR(80),

allInPings INT,
assistMePings INT,
assists INT,
baronKills INT,
basicPings INT,
bountyLevel INT,

12AssistStreakCount INT,
abilityUses INT,
acesBefore15Minutes INT,
alliedJungleMonsterKills INT,
baronTakedowns INT,
blastConeOppositeOpponentCount INT,
bountyGold INT,
buffsStolen INT,
completeSupportQuestInTime INT,
controlWardTimeCoverageInRiverOrEnemyHalf FLOAT,
controlWardsPlaced INT,
damagePerMinute FLOAT,
damageTakenOnTeamPercentage FLOAT,
dancedWithRiftHerald INT,
deathsByEnemyChamps INT,
dodgeSkillShotsSmallWindow INT,
doubleAces INT,
dragonTakedowns INT,
earliestBaron INT,
earlyLaningPhaseGoldExpAdvantage INT,
effectiveHealAndShielding INT,
elderDragonKillsWithOpposingSoul INT,
elderDragonMultikills INT,
enemyChampionImmobilizations INT,
enemyJungleMonsterKills INT,
epicMonsterKillsNearEnemyJungler INT,
epicMonsterKillsWithin30SecondsOfSpawn INT,
epicMonsterSteals INT,
epicMonsterStolenWithoutSmite INT,
firstTurretKilled INT,
flawlessAces INT,
fullTeamTakedown INT,
gameLength FLOAT,
getTakedownsInAllLanesEarlyJungleAsLaner INT,
goldPerMinute FLOAT,
hadOpenNexus INT,
immobilizeAndKillWithAlly INT,
initialBuffCount INT,
initialCrabCount INT,
jungleCsBefore10Minutes INT,
junglerTakedownsNearDamagedEpicMonster INT,
kTurretsDestroyedBeforePlatesFall INT,
kda FLOAT,
killAfterHiddenWithAlly INT,
killParticipation FLOAT,
killedChampTookFullTeamDamageSurvived INT,
killingSpreesChallenges INT,
killsNearEnemyTurret INT,
killsOnOtherLanesEarlyJungleAsLaner INT,
killsOnRecentlyHealedByAramPack INT,
killsUnderOwnTurret INT,
killsWithHelpFromEpicMonster INT,
knockEnemyIntoTeamAndKill INT,
landSkillShotsEarlyGame INT,
laneMinionsFirst10Minutes INT,
laningPhaseGoldExpAdvantage INT,
legendaryCount INT,
lostAnInhibitor INT,
maxCsAdvantageOnLaneOpponent INT,
maxKillDeficit INT,
maxLevelLeadLaneOpponent INT,
mejaisFullStackInTime INT,
moreEnemyJungleThanOpponent INT,
multiKillOneSpell INT,
multiTurretRiftHeraldCount INT,
multikills INT,
multikillsAfterAggressiveFlash INT,
outerTurretExecutesBefore10Minutes INT,
outnumberedKills INT,
outnumberedNexusKill INT,
perfectDragonSoulsTaken INT,
perfectGame INT,
pickKillWithAlly INT,
playedChampSelectPosition INT,
poroExplosions INT,
quickCleanse INT,
quickFirstTurret INT,
quickSoloKills INT,
riftHeraldTakedowns INT,
saveAllyFromDeath INT,
scuttleCrabKills INT,
skillshotsDodged INT,
skillshotsHit INT,
snowballsHit INT,
soloBaronKills INT,
soloKills INT,
stealthWardsPlaced INT,
survivedSingleDigitHpCount INT,
survivedThreeImmobilizesInFight INT,
takedownOnFirstTurret INT,
takedowns INT,
takedownsAfterGainingLevelAdvantage INT,
takedownsBeforeJungleMinionSpawn INT,
takedownsFirstXMinutes INT,
takedownsInAlcove INT,
takedownsInEnemyFountain INT,
teamBaronKills INT,
teamDamagePercentage FLOAT,
teamElderDragonKills INT,
teamRiftHeraldKills INT,
tookLargeDamageSurvived INT,
turretPlatesTaken INT,
turretTakedownsChallenges INT,
turretsTakenWithRiftHerald INT,
twentyMinionsIn3SecondsCount INT,
twoWardsOneSweeperCount INT,
unseenRecalls INT,
visionScoreAdvantageLaneOpponent FLOAT,
visionScorePerMinute FLOAT,
wardTakedowns INT,
wardTakedownsBefore20M INT,
wardsGuarded INT,
champExperience INT,
champLevel INT,
championId INT,
championName VARCHAR(15),
championTransform INT,
commandPings INT,
consumablesPurchased INT,
damageDealtToBuildings INT,
damageDealtToObjectives INT,
damageDealtToTurrets INT,
damageSelfMitigated INT,
dangerPings INT,
deaths INT,
detectorWardsPlaced INT,
doubleKills INT,
dragonKills INT,
eligibleForProgression BOOLEAN,
enemyMissingPings INT,
enemyVisionPings INT,
firstBloodAssist BOOLEAN,
firstBloodKill BOOLEAN,
firstTowerAssist BOOLEAN,
firstTowerKill BOOLEAN,
gameEndedInEarlySurrender BOOLEAN,
gameEndedInSurrender BOOLEAN,
getBackPings INT,
goldEarned INT,
goldSpent INT,
holdPings INT,
individualPosition VARCHAR(10),
inhibitorKills INT,
inhibitorTakedowns INT,
inhibitorsLost INT,
item0 INT,
item1 INT,
item2 INT,
item3 INT,
item4 INT,
item5 INT,
item6 INT,
itemsPurchased INT,
killingSprees INT,
kills INT,
lane VARCHAR(10),
largestCriticalStrike INT,
largestKillingSpree INT,
largestMultiKill INT,
longestTimeSpentLiving INT,
magicDamageDealt INT,
magicDamageDealtToChampions INT,
magicDamageTaken INT,
needVisionPings INT,
neutralMinionsKilled INT,
nexusKills INT,
nexusLost INT,
nexusTakedowns INT,
objectivesStolen INT,
objectivesStolenAssists INT,
onMyWayPings INT,
participantId INT,
pentaKills INT,
physicalDamageDealt INT,
physicalDamageDealtToChampions INT,
physicalDamageTaken INT,
placement INT,
playerAugment1 INT,
playerAugment2 INT,
playerAugment3 INT,
playerAugment4 INT,
playerScore0 INT,
playerScore1 INT,
playerScore10 INT,
playerScore11 INT,
playerScore2 INT,
playerScore3 INT,
playerScore4 INT,
playerScore5 INT,
playerScore6 INT,
playerScore7 INT,
playerScore8 INT,
playerScore9 INT,
playerSubteamId INT,
profileIcon INT,
pushPings INT,
puuid VARCHAR(100),
quadraKills INT,
riotIdGameName VARCHAR(20),
riotIdTagline VARCHAR(6),
role VARCHAR(10),
sightWardsBoughtInGame INT,
spell1Casts INT,
spell2Casts INT,
spell3Casts INT,
spell4Casts INT,
subteamPlacement INT,
summoner1Casts INT,
summoner1Id INT,
summoner2Casts INT,
summoner2Id INT,
summonerId VARCHAR(100),
summonerLevel INT,
summonerName VARCHAR(20),
teamEarlySurrendered BOOLEAN,
teamId INT,
teamPosition VARCHAR(10),
timeCCingOthers INT,
timePlayed INT,
totalAllyJungleMinionsKilled INT,
totalDamageDealt INT,
totalDamageDealtToChampions INT,
totalDamageShieldedOnTeammates INT,
totalDamageTaken INT,
totalEnemyJungleMinionsKilled INT,
totalHeal INT,
totalHealsOnTeammates INT,
totalMinionsKilled INT,
totalTimeCCDealt INT,
totalTimeSpentDead INT,
totalUnitsHealed INT,
tripleKills INT,
trueDamageDealt INT,
trueDamageDealtToChampions INT,
trueDamageTaken INT,
turretKills INT,
turretTakedowns INT,
turretsLost INT,
unrealKills INT,
visionClearedPings INT,
visionScore INT,
visionWardsBoughtInGame INT,
wardsKilled INT,
wardsPlaced INT,
win VARCHAR(10),

main_rune1_id INT,
main_rune2_id INT,
main_rune3_id INT,
main_rune4_id INT,
side_rune1_id INT,
side_rune2_id INT,
defenseRune INT,
flexRune INT,
offenseRune INT,
mainStyle INT,
subStyle INT,


TimeStampId INT,
FOREIGN KEY(puuid) REFERENCES players(puuid),
FOREIGN KEY(TimeStampId) REFERENCES TimeStamps(id)
)"""

# Tworzenie tablicy dla kolejnosci kupionych przedmiotow
SQLCreateTableItemTimeline = """CREATE TABLE TimeStamps (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item0 INT,
    item1 INT,
    item2 INT,
    item3 INT,
    item4 INT,
    item5 INT,
    item6 INT,
    item7 INT,
    item8 INT,
    item9 INT,
    item10 INT,
    item11 INT,
    item12 INT,
    item13 INT,
    item14 INT,
    item15 INT,
    item16 INT,
    item17 INT,
    item18 INT,
    item19 INT,
    item20 INT,
    item21 INT,
    item22 INT,
    item23 INT,
    item24 INT,
    item25 INT,
    item26 INT,
    item27 INT,
    item28 INT,
    item29 INT,
    item30 INT,
    item31 INT,
    item32 INT,
    item33 INT,
    item34 INT,
    item35 INT,
    item36 INT,
    item37 INT,
    item38 INT,
    item39 INT,
    item40 INT,
    item41 INT,
    item42 INT,
    item43 INT,
    item44 INT,
    item45 INT,
    item46 INT,
    item47 INT,
    item48 INT,
    item49 INT,
    item50 INT,
    item51 INT,
    item52 INT,
    item53 INT,
    item54 INT,
    item55 INT,
    item56 INT,
    item57 INT,
    item58 INT,
    item59 INT,
    
    item0TimeStamp INT,
    item1TimeStamp INT,
    item2TimeStamp INT,
    item3TimeStamp INT,
    item4TimeStamp INT,
    item5TimeStamp INT,
    item6TimeStamp INT,
    item7TimeStamp INT,
    item8TimeStamp INT,
    item9TimeStamp INT,
    item10TimeStamp INT,
    item11TimeStamp INT,
    item12TimeStamp INT,
    item13TimeStamp INT,
    item14TimeStamp INT,
    item15TimeStamp INT,
    item16TimeStamp INT,
    item17TimeStamp INT,
    item18TimeStamp INT,
    item19TimeStamp INT,
    item20TimeStamp INT,
    item21TimeStamp INT,
    item22TimeStamp INT,
    item23TimeStamp INT,
    item24TimeStamp INT,
    item25TimeStamp INT,
    item26TimeStamp INT,
    item27TimeStamp INT,
    item28TimeStamp INT,
    item29TimeStamp INT,
    item30TimeStamp INT,
    item31TimeStamp INT,
    item32TimeStamp INT,
    item33TimeStamp INT,
    item34TimeStamp INT,
    item35TimeStamp INT,
    item36TimeStamp INT,
    item37TimeStamp INT,
    item38TimeStamp INT,
    item39TimeStamp INT,
    item40TimeStamp INT,
    item41TimeStamp INT,
    item42TimeStamp INT,
    item43TimeStamp INT,
    item44TimeStamp INT,
    item45TimeStamp INT,
    item46TimeStamp INT,
    item47TimeStamp INT,
    item48TimeStamp INT,
    item49TimeStamp INT,
    item50TimeStamp INT,
    item51TimeStamp INT,
    item52TimeStamp INT,
    item53TimeStamp INT,
    item54TimeStamp INT,
    item55TimeStamp INT,
    item56TimeStamp INT,
    item57TimeStamp INT,
    item58TimeStamp INT,
    item59TimeStamp INT,
    
    LevelUp1 INT,
    LevelUp2 INT,
    LevelUp3 INT,
    LevelUp4 INT,
    LevelUp5 INT,
    LevelUp6 INT,
    LevelUp7 INT,
    LevelUp8 INT,
    LevelUp9 INT,
    LevelUp10 INT,
    LevelUp11 INT,
    LevelUp12 INT,
    LevelUp13 INT,
    LevelUp14 INT,
    LevelUp15 INT,
    LevelUp16 INT,
    LevelUp17 INT,
    LevelUp18 INT
);
"""

# Tworzenie tablicy dla Mastery
SQLCreateTableMastery = """
CREATE TABLE mastery (
puuid VARCHAR(80) PRIMARY KEY,
championId INT,
championLevel INT,
championPoints INT,
lastPlayTime INT,
championPointsSinceLastLevel INT,
championPointsUntilNextLevel INT,
chestGranted VARCHAR(10),
tokensEarned INT,
summonerId VARCHAR(80)
)"""

SQLAddUpdatePlayers = """
INSERT INTO 
players (id, name, accountId, puuid, level, profile_icon, tag, rankSolo, tierSolo, lpSolo, winSolo, loseSolo) 
VALUES (%(id)s, %(name)s, %(accountId)s, %(puuid)s, %(level)s, %(profile_icon)s, %(tag)s, %(rankSolo)s, 
%(tierSolo)s, %(lpSolo)s, %(winSolo)s, %(loseSolo)s)
ON DUPLICATE KEY UPDATE name = %(name)s, accountId = %(accountId)s, puuid = %(puuid)s, level = %(level)s, 
profile_icon = %(profile_icon)s, tag = %(tag)s, rankSolo = %(rankSolo)s, 
tierSolo = %(tierSolo)s, lpSolo = %(lpSolo)s, winSolo = %(winSolo)s, loseSolo = %(loseSolo)s
"""

SQLAddChampionBuild = """
INSERT INTO
champ_build (endOfGameResult, gameCreation, gameDuration, gameEndTimestamp, gameId, gameMode, gameStartTimestamp, 
gameType, gameVersion, mapId, platformId, queueId, tournamentCode, allInPings, assistMePings, assists, baronKills, 
basicPings, bountyLevel, 12AssistStreakCount, abilityUses, acesBefore15Minutes, alliedJungleMonsterKills, baronTakedowns, 
blastConeOppositeOpponentCount, bountyGold, buffsStolen, completeSupportQuestInTime, controlWardTimeCoverageInRiverOrEnemyHalf, 
controlWardsPlaced, damagePerMinute, damageTakenOnTeamPercentage, dancedWithRiftHerald, deathsByEnemyChamps, 
dodgeSkillShotsSmallWindow, doubleAces, dragonTakedowns, earliestBaron, earlyLaningPhaseGoldExpAdvantage, 
effectiveHealAndShielding, elderDragonKillsWithOpposingSoul, elderDragonMultikills, enemyChampionImmobilizations, 
enemyJungleMonsterKills, epicMonsterKillsNearEnemyJungler, epicMonsterKillsWithin30SecondsOfSpawn, epicMonsterSteals, 
epicMonsterStolenWithoutSmite, firstTurretKilled, flawlessAces, fullTeamTakedown, gameLength, 
getTakedownsInAllLanesEarlyJungleAsLaner, goldPerMinute, hadOpenNexus, immobilizeAndKillWithAlly, initialBuffCount, 
initialCrabCount, jungleCsBefore10Minutes, junglerTakedownsNearDamagedEpicMonster, kTurretsDestroyedBeforePlatesFall, 
kda, killAfterHiddenWithAlly, killParticipation, killedChampTookFullTeamDamageSurvived, killingSpreesChallenges, 
killsNearEnemyTurret, killsOnOtherLanesEarlyJungleAsLaner, killsOnRecentlyHealedByAramPack, killsUnderOwnTurret, 
killsWithHelpFromEpicMonster, knockEnemyIntoTeamAndKill, landSkillShotsEarlyGame, laneMinionsFirst10Minutes, 
laningPhaseGoldExpAdvantage, legendaryCount, lostAnInhibitor, maxCsAdvantageOnLaneOpponent, maxKillDeficit, 
maxLevelLeadLaneOpponent, mejaisFullStackInTime, moreEnemyJungleThanOpponent, multiKillOneSpell, multiTurretRiftHeraldCount, 
multikills, multikillsAfterAggressiveFlash, outerTurretExecutesBefore10Minutes, outnumberedKills, outnumberedNexusKill, 
perfectDragonSoulsTaken, perfectGame, pickKillWithAlly, playedChampSelectPosition, poroExplosions, quickCleanse, 
quickFirstTurret, quickSoloKills, riftHeraldTakedowns, saveAllyFromDeath, scuttleCrabKills, skillshotsDodged, 
skillshotsHit, snowballsHit, soloBaronKills, soloKills, stealthWardsPlaced, survivedSingleDigitHpCount, 
survivedThreeImmobilizesInFight, takedownOnFirstTurret, takedowns, takedownsAfterGainingLevelAdvantage, 
takedownsBeforeJungleMinionSpawn, takedownsFirstXMinutes, takedownsInAlcove, takedownsInEnemyFountain, 
teamBaronKills, teamDamagePercentage, teamElderDragonKills, teamRiftHeraldKills, tookLargeDamageSurvived, 
turretPlatesTaken, turretTakedownsChallenges, turretsTakenWithRiftHerald, twentyMinionsIn3SecondsCount, 
twoWardsOneSweeperCount, unseenRecalls, visionScoreAdvantageLaneOpponent, visionScorePerMinute, wardTakedowns, 
wardTakedownsBefore20M, wardsGuarded, champExperience, champLevel, championId, championName, championTransform, 
commandPings, consumablesPurchased, damageDealtToBuildings, damageDealtToObjectives, damageDealtToTurrets, 
damageSelfMitigated, dangerPings, deaths, detectorWardsPlaced, doubleKills, dragonKills, eligibleForProgression, 
enemyMissingPings, enemyVisionPings, firstBloodAssist, firstBloodKill, firstTowerAssist, firstTowerKill, 
gameEndedInEarlySurrender, gameEndedInSurrender, getBackPings, goldEarned, goldSpent, holdPings, individualPosition, 
inhibitorKills, inhibitorTakedowns, inhibitorsLost, item0, item1, item2, item3, item4, item5, item6, itemsPurchased, 
killingSprees, kills, lane, largestCriticalStrike, largestKillingSpree, largestMultiKill, longestTimeSpentLiving, 
magicDamageDealt, magicDamageDealtToChampions, magicDamageTaken, needVisionPings, neutralMinionsKilled, nexusKills, 
nexusLost, nexusTakedowns, objectivesStolen, objectivesStolenAssists, onMyWayPings, participantId, pentaKills, 
physicalDamageDealt, physicalDamageDealtToChampions, physicalDamageTaken, placement, playerAugment1, playerAugment2, 
playerAugment3, playerAugment4, playerScore0, playerScore1, playerScore10, playerScore11, playerScore2, playerScore3, 
playerScore4, playerScore5, playerScore6, playerScore7, playerScore8, playerScore9, playerSubteamId, profileIcon, 
pushPings, puuid, quadraKills, riotIdGameName, riotIdTagline, role, sightWardsBoughtInGame, spell1Casts, spell2Casts, 
spell3Casts, spell4Casts, subteamPlacement, summoner1Casts, summoner1Id, summoner2Casts, summoner2Id, summonerId, 
summonerLevel, summonerName, teamEarlySurrendered, teamId, teamPosition, timeCCingOthers, timePlayed, 
totalAllyJungleMinionsKilled, totalDamageDealt, totalDamageDealtToChampions, totalDamageShieldedOnTeammates, 
totalDamageTaken, totalEnemyJungleMinionsKilled, totalHeal, totalHealsOnTeammates, totalMinionsKilled, totalTimeCCDealt, 
totalTimeSpentDead, totalUnitsHealed, tripleKills, trueDamageDealt, trueDamageDealtToChampions, trueDamageTaken, 
turretKills, turretTakedowns, turretsLost, unrealKills, visionClearedPings, visionScore, visionWardsBoughtInGame, 
wardsKilled, wardsPlaced, win, main_rune1_id, main_rune2_id, main_rune3_id, main_rune4_id, side_rune1_id, side_rune2_id, 
defenseRune, flexRune, offenseRune, mainStyle, subStyle, TimeStampId)
SELECT  %(endOfGameResult)s, %(gameCreation)s, %(gameDuration)s, %(gameEndTimestamp)s, %(gameId)s, %(gameMode)s, 
%(gameStartTimestamp)s, %(gameType)s, %(gameVersion)s, %(mapId)s, %(platformId)s, %(queueId)s, %(tournamentCode)s, 
%(allInPings)s, %(assistMePings)s, %(assists)s, %(baronKills)s, %(basicPings)s, %(bountyLevel)s, %(12AssistStreakCount)s, 
%(abilityUses)s, %(acesBefore15Minutes)s, %(alliedJungleMonsterKills)s, %(baronTakedowns)s, %(blastConeOppositeOpponentCount)s, 
%(bountyGold)s, %(buffsStolen)s, %(completeSupportQuestInTime)s, %(controlWardTimeCoverageInRiverOrEnemyHalf)s, 
%(controlWardsPlaced)s, %(damagePerMinute)s, %(damageTakenOnTeamPercentage)s, %(dancedWithRiftHerald)s, %(deathsByEnemyChamps)s, 
%(dodgeSkillShotsSmallWindow)s, %(doubleAces)s, %(dragonTakedowns)s, %(earliestBaron)s, %(earlyLaningPhaseGoldExpAdvantage)s, 
%(effectiveHealAndShielding)s, %(elderDragonKillsWithOpposingSoul)s, %(elderDragonMultikills)s, %(enemyChampionImmobilizations)s, 
%(enemyJungleMonsterKills)s, %(epicMonsterKillsNearEnemyJungler)s, %(epicMonsterKillsWithin30SecondsOfSpawn)s, 
%(epicMonsterSteals)s, %(epicMonsterStolenWithoutSmite)s, %(firstTurretKilled)s, %(flawlessAces)s, %(fullTeamTakedown)s, 
%(gameLength)s, %(getTakedownsInAllLanesEarlyJungleAsLaner)s, %(goldPerMinute)s, %(hadOpenNexus)s, %(immobilizeAndKillWithAlly)s, 
%(initialBuffCount)s, %(initialCrabCount)s, %(jungleCsBefore10Minutes)s, %(junglerTakedownsNearDamagedEpicMonster)s, 
%(kTurretsDestroyedBeforePlatesFall)s, %(kda)s, %(killAfterHiddenWithAlly)s, %(killParticipation)s, 
%(killedChampTookFullTeamDamageSurvived)s, %(killingSpreesChallenges)s, %(killsNearEnemyTurret)s, 
%(killsOnOtherLanesEarlyJungleAsLaner)s, %(killsOnRecentlyHealedByAramPack)s, %(killsUnderOwnTurret)s, 
%(killsWithHelpFromEpicMonster)s, %(knockEnemyIntoTeamAndKill)s, %(landSkillShotsEarlyGame)s, %(laneMinionsFirst10Minutes)s, 
%(laningPhaseGoldExpAdvantage)s, %(legendaryCount)s, %(lostAnInhibitor)s, %(maxCsAdvantageOnLaneOpponent)s, 
%(maxKillDeficit)s, %(maxLevelLeadLaneOpponent)s, %(mejaisFullStackInTime)s, %(moreEnemyJungleThanOpponent)s, 
%(multiKillOneSpell)s, %(multiTurretRiftHeraldCount)s, %(multikills)s, %(multikillsAfterAggressiveFlash)s, 
%(outerTurretExecutesBefore10Minutes)s, %(outnumberedKills)s, %(outnumberedNexusKill)s, %(perfectDragonSoulsTaken)s, 
%(perfectGame)s, %(pickKillWithAlly)s, %(playedChampSelectPosition)s, %(poroExplosions)s, %(quickCleanse)s, 
%(quickFirstTurret)s, %(quickSoloKills)s, %(riftHeraldTakedowns)s, %(saveAllyFromDeath)s, %(scuttleCrabKills)s, 
%(skillshotsDodged)s, %(skillshotsHit)s, %(snowballsHit)s, %(soloBaronKills)s, %(soloKills)s, %(stealthWardsPlaced)s, 
%(survivedSingleDigitHpCount)s, %(survivedThreeImmobilizesInFight)s, %(takedownOnFirstTurret)s, %(takedowns)s, 
%(takedownsAfterGainingLevelAdvantage)s, %(takedownsBeforeJungleMinionSpawn)s, %(takedownsFirstXMinutes)s, 
%(takedownsInAlcove)s, %(takedownsInEnemyFountain)s, %(teamBaronKills)s, %(teamDamagePercentage)s, %(teamElderDragonKills)s, 
%(teamRiftHeraldKills)s, %(tookLargeDamageSurvived)s, %(turretPlatesTaken)s, %(turretTakedownsChallenges)s, 
%(turretsTakenWithRiftHerald)s, %(twentyMinionsIn3SecondsCount)s, %(twoWardsOneSweeperCount)s, %(unseenRecalls)s, 
%(visionScoreAdvantageLaneOpponent)s, %(visionScorePerMinute)s, %(wardTakedowns)s, %(wardTakedownsBefore20M)s, 
%(wardsGuarded)s, %(champExperience)s, %(champLevel)s, %(championId)s, %(championName)s, %(championTransform)s, 
%(commandPings)s, %(consumablesPurchased)s, %(damageDealtToBuildings)s, %(damageDealtToObjectives)s, 
%(damageDealtToTurrets)s, %(damageSelfMitigated)s, %(dangerPings)s, %(deaths)s, %(detectorWardsPlaced)s, 
%(doubleKills)s, %(dragonKills)s, %(eligibleForProgression)s, %(enemyMissingPings)s, %(enemyVisionPings)s, 
%(firstBloodAssist)s, %(firstBloodKill)s, %(firstTowerAssist)s, %(firstTowerKill)s, %(gameEndedInEarlySurrender)s, 
%(gameEndedInSurrender)s, %(getBackPings)s, %(goldEarned)s, %(goldSpent)s, %(holdPings)s, %(individualPosition)s, 
%(inhibitorKills)s, %(inhibitorTakedowns)s, %(inhibitorsLost)s, %(item0)s, %(item1)s, %(item2)s, %(item3)s, %(item4)s, 
%(item5)s, %(item6)s, %(itemsPurchased)s, %(killingSprees)s, %(kills)s, %(lane)s, %(largestCriticalStrike)s, 
%(largestKillingSpree)s, %(largestMultiKill)s, %(longestTimeSpentLiving)s, %(magicDamageDealt)s, 
%(magicDamageDealtToChampions)s, %(magicDamageTaken)s, %(needVisionPings)s, %(neutralMinionsKilled)s, %(nexusKills)s, 
%(nexusLost)s, %(nexusTakedowns)s, %(objectivesStolen)s, %(objectivesStolenAssists)s, %(onMyWayPings)s, 
%(participantId)s, %(pentaKills)s, %(physicalDamageDealt)s, %(physicalDamageDealtToChampions)s, %(physicalDamageTaken)s, 
%(placement)s, %(playerAugment1)s, %(playerAugment2)s, %(playerAugment3)s, %(playerAugment4)s, %(playerScore0)s, 
%(playerScore1)s, %(playerScore10)s, %(playerScore11)s, %(playerScore2)s, %(playerScore3)s, %(playerScore4)s, 
%(playerScore5)s, %(playerScore6)s, %(playerScore7)s, %(playerScore8)s, %(playerScore9)s, %(playerSubteamId)s, 
%(profileIcon)s, %(pushPings)s, %(puuid)s, %(quadraKills)s, %(riotIdGameName)s, %(riotIdTagline)s, %(role)s, 
%(sightWardsBoughtInGame)s, %(spell1Casts)s, %(spell2Casts)s, %(spell3Casts)s, %(spell4Casts)s, %(subteamPlacement)s, 
%(summoner1Casts)s, %(summoner1Id)s, %(summoner2Casts)s, %(summoner2Id)s, %(summonerId)s, %(summonerLevel)s, 
%(summonerName)s, %(teamEarlySurrendered)s, %(teamId)s, %(teamPosition)s, %(timeCCingOthers)s, %(timePlayed)s, 
%(totalAllyJungleMinionsKilled)s, %(totalDamageDealt)s, %(totalDamageDealtToChampions)s, %(totalDamageShieldedOnTeammates)s, 
%(totalDamageTaken)s, %(totalEnemyJungleMinionsKilled)s, %(totalHeal)s, %(totalHealsOnTeammates)s, %(totalMinionsKilled)s, 
%(totalTimeCCDealt)s, %(totalTimeSpentDead)s, %(totalUnitsHealed)s, %(tripleKills)s, %(trueDamageDealt)s, 
%(trueDamageDealtToChampions)s, %(trueDamageTaken)s, %(turretKills)s, %(turretTakedowns)s, %(turretsLost)s, %(unrealKills)s, 
%(visionClearedPings)s, %(visionScore)s, %(visionWardsBoughtInGame)s, %(wardsKilled)s, %(wardsPlaced)s, %(win)s, 
%(main_rune1_id)s, %(main_rune2_id)s, %(main_rune3_id)s, %(main_rune4_id)s, %(side_rune1_id)s, %(side_rune2_id)s, 
%(defenseRune)s, %(flexRune)s, %(offenseRune)s, %(mainStyle)s, %(subStyle)s, %(TimeStampId)s
FROM dual
WHERE NOT EXISTS (
    SELECT * FROM champ_build WHERE gameId = %(gameId)s AND summonerId = %(summonerId)s
);
"""

SQLAddItemTimeStamp = """
INSERT INTO
TimeStamps (item0, item1, item2, item3, item4, item5, item6, item7, item8, item9, item10, item11, item12, item13, item14, 
item15, item16, item17, item18, item19, item20, item21, item22, item23, item24, item25, item26, item27, item28, item29, 
item30, item31, item32, item33, item34, item35, item36, item37, item38, item39, item40, item41, item42, item43, item44, 
item45, item46, item47, item48, item49, item50, item51, item52, item53, item54, item55, item56, item57, item58, item59,
item0TimeStamp, item1TimeStamp, item2TimeStamp, item3TimeStamp, item4TimeStamp, item5TimeStamp, item6TimeStamp, 
item7TimeStamp, item8TimeStamp, item9TimeStamp, item10TimeStamp, item11TimeStamp, item12TimeStamp, item13TimeStamp, 
item14TimeStamp, item15TimeStamp, item16TimeStamp, item17TimeStamp, item18TimeStamp, item19TimeStamp, item20TimeStamp, 
item21TimeStamp, item22TimeStamp, item23TimeStamp, item24TimeStamp, item25TimeStamp, item26TimeStamp, item27TimeStamp, 
item28TimeStamp, item29TimeStamp, item30TimeStamp, item31TimeStamp, item32TimeStamp, item33TimeStamp, item34TimeStamp, 
item35TimeStamp, item36TimeStamp, item37TimeStamp, item38TimeStamp, item39TimeStamp, item40TimeStamp, item41TimeStamp, 
item42TimeStamp, item43TimeStamp, item44TimeStamp, item45TimeStamp, item46TimeStamp, item47TimeStamp, item48TimeStamp, 
item49TimeStamp, item50TimeStamp, item51TimeStamp, item52TimeStamp, item53TimeStamp, item54TimeStamp, item55TimeStamp, 
item56TimeStamp, item57TimeStamp, item58TimeStamp, item59TimeStamp)
SELECT %(item0)s, %(item1)s, %(item2)s, %(item3)s, %(item4)s, %(item5)s, %(item6)s, %(item7)s, %(item8)s, %(item9)s, 
%(item10)s, %(item11)s, %(item12)s, %(item13)s, %(item14)s, %(item15)s, %(item16)s, %(item17)s, %(item18)s, %(item19)s, 
%(item20)s, %(item21)s, %(item22)s, %(item23)s, %(item24)s, %(item25)s, %(item26)s, %(item27)s, %(item28)s, %(item29)s, 
%(item30)s, %(item31)s, %(item32)s, %(item33)s, %(item34)s, %(item35)s, %(item36)s, %(item37)s, %(item38)s, %(item39)s, 
%(item40)s, %(item41)s, %(item42)s, %(item43)s, %(item44)s, %(item45)s, %(item46)s, %(item47)s, %(item48)s, %(item49)s, 
%(item50)s, %(item51)s, %(item52)s, %(item53)s, %(item54)s, %(item55)s, %(item56)s, %(item57)s, %(item58)s, %(item59)s,
%(item0TimeStamp)s, %(item1TimeStamp)s, %(item2TimeStamp)s, %(item3TimeStamp)s, %(item4TimeStamp)s, %(item5TimeStamp)s, 
%(item6TimeStamp)s, %(item7TimeStamp)s, %(item8TimeStamp)s, %(item9TimeStamp)s, %(item10TimeStamp)s, %(item11TimeStamp)s, 
%(item12TimeStamp)s, %(item13TimeStamp)s, %(item14TimeStamp)s, %(item15TimeStamp)s, %(item16TimeStamp)s, 
%(item17TimeStamp)s, %(item18TimeStamp)s, %(item19TimeStamp)s, %(item20TimeStamp)s, %(item21TimeStamp)s, 
%(item22TimeStamp)s, %(item23TimeStamp)s, %(item24TimeStamp)s, %(item25TimeStamp)s, %(item26TimeStamp)s, 
%(item27TimeStamp)s, %(item28TimeStamp)s, %(item29TimeStamp)s, %(item30TimeStamp)s, %(item31TimeStamp)s, 
%(item32TimeStamp)s, %(item33TimeStamp)s, %(item34TimeStamp)s, %(item35TimeStamp)s, %(item36TimeStamp)s, 
%(item37TimeStamp)s, %(item38TimeStamp)s, %(item39TimeStamp)s, %(item40TimeStamp)s, %(item41TimeStamp)s, 
%(item42TimeStamp)s, %(item43TimeStamp)s, %(item44TimeStamp)s, %(item45TimeStamp)s, %(item46TimeStamp)s, 
%(item47TimeStamp)s, %(item48TimeStamp)s, %(item49TimeStamp)s, %(item50TimeStamp)s, %(item51TimeStamp)s, 
%(item52TimeStamp)s, %(item53TimeStamp)s, %(item54TimeStamp)s, %(item55TimeStamp)s, %(item56TimeStamp)s, 
%(item57TimeStamp)s, %(item58TimeStamp)s, %(item59TimeStamp)s
FROM dual
"""

SQLGetLastIdTimeStamp = """SELECT id 
FROM TimeStamps
ORDER BY id DESC
LIMIT 1"""



"""
MyCursor.execute("SELECT * FROM players WHERE id='12341234'")
records = MyCursor.fetchall()
print(records)
"""

#MyCursor.execute(SQLCreateTablePlayers)
#mydb.commit()
#MyCursor.execute(SQLCreateTableItemTimeline)
#mydb.commit()
#MyCursor.execute(SQLCreateTableMastery)
#mydb.commit()
#MyCursor.execute(SQLCreateTableChampBuild)
#mydb.commit()






